- label: 'Test Build'
  command:
    - if [ ! -z "$MERGE_BRANCH" ]; then git merge $MERGE_BRANCH -m "merging $MERGE_BRANCH"; fi
    - curl https://rebar3.s3.amazonaws.com/rebar3 -o ./rebar3
    - chmod +x rebar3
    - ./rebar3 plugins upgrade rebar3_format
    - ./rebar3 format --verify
    - ./rebar3 dialyzer || true # avoid plt warnings
    - aws s3 sync s3://adroll-misc/rtb/dinerl/ . --exclude "*" --include "*plt" --no-follow-symlinks
    - ./rebar3 test
    - aws s3 sync . s3://adroll-misc/rtb/dinerl/ --exclude "*" --include "*plt" --no-follow-symlinks
  agents:
    queue: 'rtb'
